name: Continuous Integration

on:
  push:
    tags: ['*']
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Scala
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
      - name: Cache Verilator
        id: cache-verilator
        uses: actions/cache@v4
        with:
          path: verilator-src
          key: ${{ runner.os }}-verilator-v5.028

      - name: Compile and Install Verilator
        run: |
          sudo apt-get update
          sudo apt-get install -y git perl python3 make autoconf g++ flex bison ccache libgoogle-perftools-dev numactl perl-doc libfl2 libfl-dev zlibc zlib1g zlib1g-dev
          
          if [ ! -d "verilator-src" ]; then
            echo "Cache miss: Cloning and building Verilator from source..."
            git clone -b v5.028 https://github.com/verilator/verilator verilator-src
            cd verilator-src
            autoconf
            ./configure
            make -j$(nproc)
            cd ..
          else
            echo "Cache hit: Skip building."
          fi
          
          cd verilator-src
          sudo make install
          
          verilator --version
      - name: mill Test
        run: ./mill _.test
