name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ci:
    name: Scala Test with Verilator
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11

      - name: Setup Verilator via Conda
        uses: mamba-org/setup-micromamba@v1
        with:
          environment-name: verilator-env
          create-args: >-
            verilator=5.028
            -c conda-forge
          cache-environment: true
          init-shell: bash

      - name: Run Mill Tests
        shell: bash -l {0}
        run: |
          verilator --version
          ./mill _.test