name: Continuous Integration

on:
  push:
    tags: ['*']
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Cache Scala
        uses: coursier/cache-action@v6
      - name: Setup Scala
        uses: coursier/setup-action@v1
        with:
          jvm: adopt:11
          apps: sbt
      - name: Setup Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y verilator
          sudo mv /usr/bin/verilator /usr/bin/verilator-orig
          echo '#!/bin/bash' | sudo tee /usr/bin/verilator
          echo '/usr/bin/verilator-orig -Wno-WIDTHEXPAND "$@"' | sudo tee -a /usr/bin/verilator
          sudo chmod +x /usr/bin/verilator
          verilator --version

      - name: mill Test
        run: ./mill _.test
